// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-SCyv7KRq6Zx0wW2PAQVfi7CEe0Kgnc',
    appId: '1:444814870060:web:f3de356bf9367a53197389',
    messagingSenderId: '444814870060',
    projectId: 'book-my-time-eb5fc',
    authDomain: 'book-my-time-eb5fc.firebaseapp.com',
    storageBucket: 'book-my-time-eb5fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHqwntwC7Zm_-3t1K5YO5xYi3ty8kf8Hc',
    appId: '1:444814870060:android:4e9d232f9c4255c3197389',
    messagingSenderId: '444814870060',
    projectId: 'book-my-time-eb5fc',
    storageBucket: 'book-my-time-eb5fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzY9Vd4TlGQHh8K2O4Er8Qk-CynXHx0NQ',
    appId: '1:444814870060:ios:9e2b7bfb8fb18043197389',
    messagingSenderId: '444814870060',
    projectId: 'book-my-time-eb5fc',
    storageBucket: 'book-my-time-eb5fc.appspot.com',
    iosBundleId: 'com.example.bookmytime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzY9Vd4TlGQHh8K2O4Er8Qk-CynXHx0NQ',
    appId: '1:444814870060:ios:fd5dd22cc1ee49d8197389',
    messagingSenderId: '444814870060',
    projectId: 'book-my-time-eb5fc',
    storageBucket: 'book-my-time-eb5fc.appspot.com',
    iosBundleId: 'com.example.bookmytime.RunnerTests',
  );
}
